### ISSUE TITLE
not working in blender 4.3

### ISSUE THREAD

**Issue by pooyapower** [BenjaminSauder/SimpleLattice#14]
it works fine on 4.2 but it's not working in blender 4.3 

`Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-4.3.0-beta+v43.528df9033623-windows.amd64-release\4.3\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1389, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\blender-4.3.0-beta+v43.528df9033623-windows.amd64-release\4.3\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2453, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "C:\Program Files\Blender Foundation\blender-4.3.0-beta+v43.528df9033623-windows.amd64-release\4.3\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2584, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "C:\Program Files\Blender Foundation\blender-4.3.0-beta+v43.528df9033623-windows.amd64-release\4.3\scripts\startup\bl_operators\userpref.py", line 822, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "C:\Program Files\Blender Foundation\blender-4.3.0-beta+v43.528df9033623-windows.amd64-release\4.3\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: 'module' object has no attribute 'VIEW3D_MT_gpencil_edit_context_menu'
`

**Comment by muchfolk** [comment]
我在安装了blender正式版后，也发现了这个问题，期待您的更新 谢谢！

**Comment by mahreeoocedev01** [comment]
I created a pull request fixing the issue.

In the meantime, you can just copy the line from the change found here:
https://github.com/BenjaminSauder/SimpleLattice/pull/15/commits/b2e39919ad8b7b6d2c3318744b1ce6205b591e5f

**Comment by pooyapower** [comment]
> I created a pull request fixing the issue.
> 
> In the meantime, you can just copy the line from the change found here: [b2e3991](https://github.com/BenjaminSauder/SimpleLattice/commit/b2e39919ad8b7b6d2c3318744b1ce6205b591e5f)

thanks for the solution, there is still one little problem, everytime I open the blender app, i have to reactivate the addon.

**Comment by Shliosas** [comment]
Best addon ! how do i get it to work on a new blender ? :(

**Comment by MetinSeven** [comment]
> Best addon ! how do i get it to work on a new blender ? :(

Until Benjamin updates SimpleLattice, the latest Blender (I think 5.0) has a native function to add a Lattice to an object. Press Shift + A and go to the Lattice submenu.
